import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppQueryProvider } from "@/lib/query/query-provider";
import AuthProvider from "@/providers/AuthProvider";
import { UnverifiedEmailBanner } from "@/components/layout/unverified-email-banner";
import { CartDrawer } from "@/components/cart/cart-drawer";
import { CartSyncListener } from "@/components/cart/cart-sync-listener";
import { Toaster } from "@/components/ui/sonner";
import { CartIcon } from "@/components/cart/cart-icon";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppQueryProvider>
          <AuthProvider>
            <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
              <CartIcon />
            </div>
            <UnverifiedEmailBanner />
            {children}
            <CartDrawer />
            <CartSyncListener />
            <Toaster position="top-center" />
          </AuthProvider>
        </AppQueryProvider>
      </body>
    </html>
  );
}
